### ISSUE TITLE
md乱码问题，规范md

### ISSUE THREAD

**Issue by weihubeats** [lyh200/dynamic-tp-spring-cloud-starter#2]
md乱码问题
![image](https://user-images.githubusercontent.com/42484192/149862859-74b45832-2394-4d19-bb9b-3e7045352f6c.png)
![image](https://user-images.githubusercontent.com/42484192/149862911-cafbce65-fec4-4d4d-8b18-dddb31d0b3de.png)

**Comment by lyh200** [comment]
👍
